services:
  redis:
    restart: on-failure
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"

  web1:
    restart: on-failure
    build: ./web
    hostname: web1
    volumes:
      - ./web:/var/www/html
    depends_on:
      - redis
  web2:
    restart: on-failure
    build: ./web
    hostname: web2
    volumes:
      - ./web:/var/www/html
    depends_on:
      - redis

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    #      - '8081:443'
    depends_on:
      - web1
#    secrets:
#      - ssl_cert
#      - ssl_key

#secrets:
#  ssl_cert:
#    file: ./keys/natez.art.crt
#  ssl_key:
#    file: ./keys/natez.art.key
